# Generated by Django 5.1.7 on 2025-03-22 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(help_text="Driver's current location (e.g., City, State)", max_length=255)),
                ('pickup_location', models.CharField(help_text='Pickup location (e.g., Warehouse address)', max_length=255)),
                ('dropoff_location', models.CharField(help_text='Dropoff location (e.g., Customer address)', max_length=255)),
                ('current_cycle_used', models.FloatField(help_text='Current cycle hours used (70-hour/8-day rule)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Log date (YYYY-MM-DD)')),
                ('total_miles', models.FloatField(help_text='Total miles driven today')),
                ('driving_time', models.FloatField(help_text='Total driving time (hours)')),
                ('on_duty_time', models.FloatField(help_text='On-duty not driving time (hours)')),
                ('off_duty_time', models.FloatField(help_text='Off-duty time (hours)')),
                ('rest_breaks', models.FloatField(default=0.5, help_text='30-minute rest breaks (count)')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trips.trip')),
            ],
        ),
    ]
